services:
  db_blog:
    image: postgres:latest
    container_name: db_blog_container
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DB_Blog
    volumes:
      - ./postgreSql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
